# syntax=docker/dockerfile:1
FROM nvidia/cuda:12.6.3-base-ubuntu24.04@sha256:c87e78933f4c16e3272123bf2f75537306596d0fbaa395a29696a22786e5ee0e AS cuda-compat

FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleocr-vl:latest-nvidia-gpu@sha256:ad0b1f056a76967f9191cd06398e8babb21b49a4673a28c3de5fd31f481884db

USER root
RUN --mount=type=bind,from=cuda-compat,source=/usr/local/cuda-12.6/compat,target=/opt/cuda-compat,ro \
    LD_LIBRARY_PATH=/opt/cuda-compat paddleocr install_hpi_deps gpu
USER paddleocr

WORKDIR /opt/ade
COPY service.py /opt/ade/service.py

EXPOSE 8118

CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8118"]
